<?php
function activities_schema() {
  $schema['activity_data'] = array(
    'description' => 'Stores Data of activity form.',
    'fields' => array(
      'first_name' => array(
        'type' => 'varchar',
        'length' => 50,
        'not null' => TRUE,
      ),

      'last_name' => array(
        'type' => 'varchar',
        'length' => 50,
        'not null' => TRUE,
      ),
    ),
  );
  return $schema;
}